draw_config:
  check_layers: true
parse_config:
  skip_is_main_pad: true
  zmk_remove_keycode_prefix: ["&kp", "&mt", "&lt"]
  raw_binding_map:
    # あなたが定義した日本語配列の記号すべて
    "JP_DQUOTE": "\""
    "JP_AMPERSAND": "&"
    "JP_QUOTE": "'"
    "JP_EQUAL": "="
    "JP_CARET": "^"
    "JP_YEN": "¥"
    "JP_PLUS": "+"
    "JP_TILDE": "~"
    "JP_PIPE": "|"
    "JP_AT": "@"
    "JP_COLON": ":"
    "JP_ASTERISK": "*"
    "JP_BACKQUOTE": "`"
    "JP_UNDERSCORE": "_"
    "JP_LBRACKET": "["
    "JP_RBRACKET": "]"
    "JP_LPAREN": "("
    "JP_RPAREN": ")"
    "JP_LBRACE": "{"
    "JP_RBRACE": "}"
    "JP_KANA": "かな"
    "JP_EISU": "英数"
    "JP_HANZEN": "半/全"

    # その他、スキャンコードや長押しキーの調整
    "0x89": "_"
    "0x87": "¥"
    "LEFT_SHIFT ENTER": "Shift/Ent"
    "RIGHT_SHIFT JP_UNDERSCORE": "Shift/_"
    "LEFT_WIN BACKSPACE": "Win/BS"
    "RIGHT_CONTROL ESCAPE": "Ctrl/Esc"
    "1 SPACE": "L1/Space"
    "2 INTERNATIONAL_5": "L2/無変換"
    "4 TAB": "L4/Tab"
