name: Draw Keymap
on:
  push:
    paths:
      - 'config/keymap.keymap'
      - 'config.yaml'
      - 'info.json'
  workflow_dispatch: # 手動実行ボタンも追加しておきます

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Draw
        run: |
          # 1. 解析（config.yamlを適用して文字置換）
          keymap -c config.yaml parse -z config/keymap.keymap > keymap_data.yaml
          # 2. 描画（info.jsonを適用してSVG作成）
          keymap -c config.yaml draw -j config/info.json keymap_data.yaml > keymap_display.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 生成されたsvgを確実にステージングに追加
          git add keymap_display.svg
          # 変更がある場合のみコミットし、なければ終了
          git commit -m "Update keymap image" || exit 0
          git push

      - name: Push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add keymap_display.svg
          git commit -m "Update keymap SVG" || exit 0
          git push
